apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: understand-passkey
  labels:
    app: understand-passkey
  annotations:
    cert-manager.io/cluster-issuer: "cloudflare"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - understand-passkeys-with.a-cup-of.coffee
      secretName: understand-passkey-tls
  rules:
    - host: understand-passkeys-with.a-cup-of.coffee
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: understand-passkey
                port:
                  number: 80
