apiVersion: v1
kind: Service
metadata:
  name: understand-passkey
  labels:
    app: understand-passkey
spec:
  type: ClusterIP
  selector:
    app: understand-passkey
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
